---
title: "NF-OSI Data Sharing Plan (DHART-SPORE)"
author: "NF-OSI DCC"
date: ""
output:
  html_document:
    includes:
      in_header: ../../sections/header.html
      after_body: ../../sections/footer.html 
    theme: paper
    css: ../../www/style.css
  pdf_document: default
params:
  fundingAgencyFullName: Developmental and Hyperactive Ras Tumor (DHART) SPORE
  fundingAgency: DHART-SPORE
  standalone: No
  formMetaInput: !r list(name = "formFunderVersion", type = "hidden", value = "DHART-SPORE", form = "dsp")
  data: "../tests/test.json"
---

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
sections <- "../../sections/"
```

::: {#expository-section}
<!-- the commitment section is NOT the common used for CTF and NTAP -->
```{r child = paste0('preamble_commitment_data_sharing.Rmd')}
```

```{r child = paste0(sections, 'preamble_data_sharing.Rmd')}
```

```{r child = paste0(sections, 'preamble_data_licensing.Rmd')}
```
:::

::: {#main-section }
```{r child = paste0(sections, 'dsp_common.Rmd')}
```

```{r child = paste0(sections, 'gov_SA.Rmd')}
```
:::

::: {#addendum-1 .addendum-section style="display: none;"}
```{r child = paste0(sections, 'addendum_1.md')}
```
:::

::: {#addendum-2 .addendum-section style="display: none;"}
```{r child = paste0(sections, 'addendum_2.Rmd')}
```
:::

::: {#submit-section}
**Form Date** `r RIA(DSP$filledDate)`

`r formSubmit(DSP$submit)`
</br>
We will review and send you a copy of what we have on file, but feel free to use `Ctrl+P` to save a copy now.  
If any adjustments to this plan need to be made, please email nf-osi@sagebionetworks.org and your `r params$fundingAgency` contact.
<!--hidden fields for tracking form meta, e.g. versions" -->
`r RIA(params$formMetaInput)`
`r RIA(DSP$dspCommonVersion)`
:::

