---
title: "Addendum 1"
author: "Sage Bionetworks"
date: "4/11/2022"
output: html_document
params: 
  fundingAgency: XXX Foundation
  DCC: NF-OSI
  embargoPeriod: the embargo period
---

The goal of this data sharing plan is to support the **FAIR Data Principles (Findable, Accessible, Interoperable, and Reusable)**. 
It serves as a general guide and allows the data contributor to describe the data that will be shared and how/when they will be released.

## Commitment to Data Sharing

`r params$fundingAgency` grantees are invited to upload data generated in the performance of research funded by the `r params$fundingAgency` program into a customized [Synapse](https://www.synapse.org/) `r params$DCC` project as soon as possible after being generated. 
Data will be embargoed from the public and accessible only to the data contributor and the `r params$DCC` data curation team at Sage Bionetworks during the award period and until the embargo end date provided in the form below. 
The embargo period will end earlier if the data is published or at the data contributor’s discretion.  
After the embargo period, the data will be made available to the broader research community via the Synapse platform.
