---
title: "Addendum 1"
author: "Sage Bionetworks"
date: "4/11/2022"
output: html_document
params: 
  DCC: NF-OSI
---

## Addendum 1 {#Addendum-1}

### Guidelines for human sample data

Prior to submitting data each contributor will ensure that:

- The data submission and subsequent data sharing for general research purposes are consistent with applicable national, tribal and state laws and regulations as well as institutional policies.

- An Institutional Review Board/Privacy Board or equivalent body, as applicable, has assured that submission and subsequent sharing of human data for general research purposes (including data such as that being submitted by the contributor) are consistent with the informed consent of study participants from whom the data was obtained.

- The identity of research participants will not be disclosed to `r params$DCC` members and/or Sage Bionetworks:

    - All submitted human data has been de-identified according to HHS 45 CFR 46.102(f) regulation and the de-identification standards of the HIPAA privacy rules, 45 CFR § 164.514(b), so that individual subjects’ identities cannot be ascertained by `r params$DCC` members or through secondary data use.

    - The de-identified data has been assigned random, unique identifier codes that legally may be made visible to anyone on the web (i.e., the identifier codes do not include any information that can be used to re-identify the study participant).

    - The study PI will inform Sage Bionetworks if any metadata contains potentially identifiable information.

    - The data contributor will review data after submission, before they are released, to verify that no identifying information has been submitted accidentally.

    - Filenames will not contain identifiable information and legally may be made visible to anyone on the web.

- The study PI will notify Sage Bionetworks if there are quality concerns about any data that has been submitted (not limited to potentially identifiable information). 

- Data quality corrections will be submitted as soon as possible.

