---
title: "Sensitivity Assessment Section"
author: "NF-OSI DCC"
date: "4/11/2022"
output:
  html_document: default
  pdf_document: default
params:
  fragment: No
  data: null
---

```{r echo=FALSE, message=FALSE}
if(FALSE) {
  suppressPackageStartupMessages(source(list.files("../R", full.names = T)))
  config <- getConfig("gov_SA_config.yml")
  DSP <- config$Inputs
}
```

#### Data Sensitivity Assessment

_Please fill in the following to help us understand the nature of the data and help determine if additional governance forms are needed._

These data:

  `r RIA(DSP$govSA_1)`  (1) Are not sensitive (i.e., do not meet any of the criteria below), and can be shared broadly without restriction after the project embargo period ends OR
              
  `r RIA(DSP$govSA_2)`  (2) Are derived from humans OR
              
  `r RIA(DSP$govSA_3)`  (3) Are not derived from humans but for some other reason cannot be shared openly/need to be shared with restrictions on access or data use after the project period ends OR
              
  `r RIA(DSP$govSA_4)`  (4) I am not sure whether these data are sensitive.   

::: {#addendum-required style="display: none;"}
For possibly sensitive data (selection 2, 3, or 4), please read [Addendum 1](#Addendum-1) and fill out [Addendum 2](#Addendum-2) as well.
:::

**Non-human data only:** Instead of CC0 (default) I would like the data to be licensed as `r RIA(DSP$projectDataLicense)`. 

