---
title: "NF-OSI Data Sharing Plan (DHART-SPORE)"
author: "NF-OSI DCC"
date: ""
output:
  html_document:
    includes:
      in_header: header.html
      after_body: footer.html 
    theme: paper
    css: style.css
  pdf_document: default
params:
  # -- DATA -- #
  data: null
  # -- Section_Commitment -- #
  fundingAgencyFullName: Developmental and Hyperactive Ras Tumor (DHART) SPORE
  DCC: NF-OSI
  embargoPeriod: the embargo period
  # -- Section_Data_Sharing -- #
  helpDocsLink: https://help.nf.synapse.org/NFdocs/How-to-Format-Your-Data.2110980453.html
  dccEmail: nf-osi@sagebionetworks.org
  # DCC: NF-OSI # common params already defined with Section_Commitment
  portalName: NF Data Portal
  portalURL: http://nfdataportal.org/
  fundingAgency: DHART-SPORE
  # embargoPeriod: the embargo period # common params already defined
  community: NF
  # -- DSP_Core -- #
  dsp_core_config: dsp_core_config.yml
  # -- Custom meta/parameters for this form -- #
  dsp_custom_config: dsp_custom_config.yml
  # -- Gov -- #
  SA_config: gov_SA_config.yml
  addendum_2_config: addendum_2_config.yml
---

```{r setup, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(formd)
formChecklistContext(params$dsp_custom_config)
.F <- formInputContext(params$dsp_custom_config, params$data)
```

::: {#expository-section}
```{r child = 'Section_Commitment.Rmd'}
```

```{r child = 'Section_Data_Sharing.Rmd'}
```

```{r child = 'Section_Data_Licensing.Rmd'}
```
:::

::: {#main-section }
```{r child = 'DSP_Core.Rmd'}
```

```{r child = 'Sensitivity_Assessment.Rmd'}
```
:::

::: {#addendum-1 .addendum-section style="display: none;"}
```{r child = 'Addendum_1.Rmd'}
```
:::

::: {#addendum-2 .addendum-section style="display: none;"}
```{r child = 'Addendum_2.Rmd'}
```
:::

::: {#submit-section}
**Form Date** `r RIA(.F$filledDate)`

`r formSubmit(.F$submit)`
</br>
We will review and send you a copy of what we have on file, but feel free to use `Ctrl+P` to save a copy now.  
If any adjustments need to be made, please email `r params$dccEmail` and your `r params$fundingAgency` contact.

<!--hidden fields for tracking form meta, e.g. versions" -->
`r RIA(.F$formCustomVersion)`
:::

