The goal of this data sharing plan is to support the **FAIR Data Principles (Findable, Accessible, Interoperable, and Reusable)**. 
It serves as a general guide and allows the data contributor to describe the data that will be shared and how/when they will be released.

## Commitment to Data Sharing

Data contributors are required by the `r params$fundingAgencyFullName` to upload data generated in the performance of research funded by or on behalf of `r params$fundingAgency` or one of its affiliates into a customized [Synapse](https://www.synapse.org/) NF-OSI project space by the associated progress report deadline, though contributors are encouraged to upload data as soon as possible after being generated. 
Data will be embargoed from the public and accessible only to the data contributor, the NF-OSI data curation team at Sage Bionetworks, `r params$fundingAgency` staff and consultants, during the award period and for `r params$embargoPeriod` after the end date of the award, unless your contract with `r params$fundingAgency` states otherwise. 
The embargo period will end earlier if the data is published or at the data contributor’s discretion. 
After the embargo period, the data will be made available to the broader research community via the Synapse platform. 
Any requests by an investigator for an extension of the embargo period (e.g., due to a delay in primary publication), must be made in writing to the `r params$fundingAgency` Project Manager. 